#!/bin/bash
# initialize for dials 3
. /nsls2/software/mx/dials-v3-7-2/dials_env.sh
file=$1
dirname=${file%/*}
basename=${file##*/}
target=${dirname}/${basename%.*}
echo "processing $PWD $file"
cctbx.python ~/bin/h5recompress.py ${target} lz4
cctbx.python ~/bin/h5recompress.py ${target} bslz4
cctbx.python ~/bin/h5recompress.py ${target} zstd 2
cctbx.python ~/bin/h5recompress.py ${target} zstd 3
cctbx.python ~/bin/h5recompress.py ${target} zstd 4
cctbx.python ~/bin/h5recompress.py ${target} zstd 5
cctbx.python ~/bin/h5recompress.py ${target} zstd 6
cctbx.python ~/bin/h5recompress.py ${target} bszstd 2
cctbx.python ~/bin/h5recompress.py ${target} bszstd 3
cctbx.python ~/bin/h5recompress.py ${target} bszstd 4
cctbx.python ~/bin/h5recompress.py ${target} bszstd 5
cctbx.python ~/bin/h5recompress.py ${target} bszstd 6

