#!/bin/bash
dataset=$1
time bash ./timing2.bash 96 "$dataset" "lz4"
echo time bash ./timing2.bash 96 "$dataset" "lz4" 
time bash ./timing2.bash 96 "$dataset" "bslz4"
echo time bash ./timing2.bash 96 "$dataset" "bslz4" 
time bash ./timing2.bash 96 "$dataset" "zstd 2"
echo time bash ./timing2.bash 96 "$dataset" "zstd 2" 
time bash ./timing2.bash 96 "$dataset" "zstd 3"
echo time bash ./timing2.bash 96 "$dataset" "zstd 3" 
time bash ./timing2.bash 96 "$dataset" "zstd 4"
echo time bash ./timing2.bash 96 "$dataset" "zstd 4" 
time bash ./timing2.bash 96 "$dataset" "zstd 5"
echo time bash ./timing2.bash 96 "$dataset" "zstd 5" 
time bash ./timing2.bash 96 "$dataset" "zstd 6"
echo time bash ./timing2.bash 96 "$dataset" "zstd 6" 
time bash ./timing2.bash 96 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 96 "$dataset" "bszstd 2" 
time bash ./timing2.bash 96 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 96 "$dataset" "bszstd 3" 
time bash ./timing2.bash 96 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 96 "$dataset" "bszstd 4" 
time bash ./timing2.bash 96 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 96 "$dataset" "bszstd 5" 
time bash ./timing2.bash 96 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 96 "$dataset" "bszstd 6" 
time bash ./timing2.bash 64 "$dataset" "lz4"
echo time bash ./timing2.bash 64 "$dataset" "lz4" 
time bash ./timing2.bash 64 "$dataset" "bslz4"
echo time bash ./timing2.bash 64 "$dataset" "bslz4" 
time bash ./timing2.bash 64 "$dataset" "zstd 2"
echo time bash ./timing2.bash 64 "$dataset" "zstd 2" 
time bash ./timing2.bash 64 "$dataset" "zstd 3"
echo time bash ./timing2.bash 64 "$dataset" "zstd 3" 
time bash ./timing2.bash 64 "$dataset" "zstd 4"
echo time bash ./timing2.bash 64 "$dataset" "zstd 4" 
time bash ./timing2.bash 64 "$dataset" "zstd 5"
echo time bash ./timing2.bash 64 "$dataset" "zstd 5" 
time bash ./timing2.bash 64 "$dataset" "zstd 6"
echo time bash ./timing2.bash 64 "$dataset" "zstd 6" 
time bash ./timing2.bash 64 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 64 "$dataset" "bszstd 2" 
time bash ./timing2.bash 64 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 64 "$dataset" "bszstd 3" 
time bash ./timing2.bash 64 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 64 "$dataset" "bszstd 4" 
time bash ./timing2.bash 64 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 64 "$dataset" "bszstd 5" 
time bash ./timing2.bash 64 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 64 "$dataset" "bszstd 6" 
time bash ./timing2.bash 32 "$dataset" "lz4"
echo time bash ./timing2.bash 32 "$dataset" "lz4" 
time bash ./timing2.bash 32 "$dataset" "bslz4"
echo time bash ./timing2.bash 32 "$dataset" "bslz4" 
time bash ./timing2.bash 32 "$dataset" "zstd 2"
echo time bash ./timing2.bash 32 "$dataset" "zstd 2" 
time bash ./timing2.bash 32 "$dataset" "zstd 3"
echo time bash ./timing2.bash 32 "$dataset" "zstd 3" 
time bash ./timing2.bash 32 "$dataset" "zstd 4"
echo time bash ./timing2.bash 32 "$dataset" "zstd 4" 
time bash ./timing2.bash 32 "$dataset" "zstd 5"
echo time bash ./timing2.bash 32 "$dataset" "zstd 5" 
time bash ./timing2.bash 32 "$dataset" "zstd 6"
echo time bash ./timing2.bash 32 "$dataset" "zstd 6" 
time bash ./timing2.bash 32 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 32 "$dataset" "bszstd 2" 
time bash ./timing2.bash 32 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 32 "$dataset" "bszstd 3" 
time bash ./timing2.bash 32 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 32 "$dataset" "bszstd 4" 
time bash ./timing2.bash 32 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 32 "$dataset" "bszstd 5" 
time bash ./timing2.bash 32 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 32 "$dataset" "bszstd 6" 
time bash ./timing2.bash 16 "$dataset" "lz4"
echo time bash ./timing2.bash 16 "$dataset" "lz4" 
time bash ./timing2.bash 16 "$dataset" "bslz4"
echo time bash ./timing2.bash 16 "$dataset" "bslz4" 
time bash ./timing2.bash 16 "$dataset" "zstd 2"
echo time bash ./timing2.bash 16 "$dataset" "zstd 2" 
time bash ./timing2.bash 16 "$dataset" "zstd 3"
echo time bash ./timing2.bash 16 "$dataset" "zstd 3" 
time bash ./timing2.bash 16 "$dataset" "zstd 4"
echo time bash ./timing2.bash 16 "$dataset" "zstd 4" 
time bash ./timing2.bash 16 "$dataset" "zstd 5"
echo time bash ./timing2.bash 16 "$dataset" "zstd 5" 
time bash ./timing2.bash 16 "$dataset" "zstd 6"
echo time bash ./timing2.bash 16 "$dataset" "zstd 6" 
time bash ./timing2.bash 16 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 16 "$dataset" "bszstd 2" 
time bash ./timing2.bash 16 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 16 "$dataset" "bszstd 3" 
time bash ./timing2.bash 16 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 16 "$dataset" "bszstd 4" 
time bash ./timing2.bash 16 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 16 "$dataset" "bszstd 5" 
time bash ./timing2.bash 16 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 16 "$dataset" "bszstd 6" 
time bash ./timing2.bash 8 "$dataset" "lz4"
echo time bash ./timing2.bash 8 "$dataset" "lz4" 
time bash ./timing2.bash 8 "$dataset" "bslz4"
echo time bash ./timing2.bash 8 "$dataset" "bslz4" 
time bash ./timing2.bash 8 "$dataset" "zstd 2"
echo time bash ./timing2.bash 8 "$dataset" "zstd 2" 
time bash ./timing2.bash 8 "$dataset" "zstd 3"
echo time bash ./timing2.bash 8 "$dataset" "zstd 3" 
time bash ./timing2.bash 8 "$dataset" "zstd 4"
echo time bash ./timing2.bash 8 "$dataset" "zstd 4" 
time bash ./timing2.bash 8 "$dataset" "zstd 5"
echo time bash ./timing2.bash 8 "$dataset" "zstd 5" 
time bash ./timing2.bash 8 "$dataset" "zstd 6"
echo time bash ./timing2.bash 8 "$dataset" "zstd 6" 
time bash ./timing2.bash 8 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 8 "$dataset" "bszstd 2" 
time bash ./timing2.bash 8 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 8 "$dataset" "bszstd 3" 
time bash ./timing2.bash 8 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 8 "$dataset" "bszstd 4" 
time bash ./timing2.bash 8 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 8 "$dataset" "bszstd 5" 
time bash ./timing2.bash 8 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 8 "$dataset" "bszstd 6" 
time bash ./timing2.bash 4 "$dataset" "lz4"
echo time bash ./timing2.bash 4 "$dataset" "lz4" 
time bash ./timing2.bash 4 "$dataset" "bslz4"
echo time bash ./timing2.bash 4 "$dataset" "bslz4" 
time bash ./timing2.bash 4 "$dataset" "zstd 2"
echo time bash ./timing2.bash 4 "$dataset" "zstd 2" 
time bash ./timing2.bash 4 "$dataset" "zstd 3"
echo time bash ./timing2.bash 4 "$dataset" "zstd 3" 
time bash ./timing2.bash 4 "$dataset" "zstd 4"
echo time bash ./timing2.bash 4 "$dataset" "zstd 4" 
time bash ./timing2.bash 4 "$dataset" "zstd 5"
echo time bash ./timing2.bash 4 "$dataset" "zstd 5" 
time bash ./timing2.bash 4 "$dataset" "zstd 6"
echo time bash ./timing2.bash 4 "$dataset" "zstd 6" 
time bash ./timing2.bash 4 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 4 "$dataset" "bszstd 2" 
time bash ./timing2.bash 4 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 4 "$dataset" "bszstd 3" 
time bash ./timing2.bash 4 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 4 "$dataset" "bszstd 4" 
time bash ./timing2.bash 4 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 4 "$dataset" "bszstd 5" 
time bash ./timing2.bash 4 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 4 "$dataset" "bszstd 6" 
time bash ./timing2.bash 2 "$dataset" "lz4"
echo time bash ./timing2.bash 2 "$dataset" "lz4" 
time bash ./timing2.bash 2 "$dataset" "bslz4"
echo time bash ./timing2.bash 2 "$dataset" "bslz4" 
time bash ./timing2.bash 2 "$dataset" "zstd 2"
echo time bash ./timing2.bash 2 "$dataset" "zstd 2" 
time bash ./timing2.bash 2 "$dataset" "zstd 3"
echo time bash ./timing2.bash 2 "$dataset" "zstd 3" 
time bash ./timing2.bash 2 "$dataset" "zstd 4"
echo time bash ./timing2.bash 2 "$dataset" "zstd 4" 
time bash ./timing2.bash 2 "$dataset" "zstd 5"
echo time bash ./timing2.bash 2 "$dataset" "zstd 5" 
time bash ./timing2.bash 2 "$dataset" "zstd 6"
echo time bash ./timing2.bash 2 "$dataset" "zstd 6" 
time bash ./timing2.bash 2 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 2 "$dataset" "bszstd 2" 
time bash ./timing2.bash 2 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 2 "$dataset" "bszstd 3" 
time bash ./timing2.bash 2 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 2 "$dataset" "bszstd 4" 
time bash ./timing2.bash 2 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 2 "$dataset" "bszstd 5" 
time bash ./timing2.bash 2 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 2 "$dataset" "bszstd 6" 
time bash ./timing2.bash 1 "$dataset" "lz4"
echo time bash ./timing2.bash 1 "$dataset" "lz4" 
time bash ./timing2.bash 1 "$dataset" "bslz4"
echo time bash ./timing2.bash 1 "$dataset" "bslz4" 
time bash ./timing2.bash 1 "$dataset" "zstd 2"
echo time bash ./timing2.bash 1 "$dataset" "zstd 2" 
time bash ./timing2.bash 1 "$dataset" "zstd 3"
echo time bash ./timing2.bash 1 "$dataset" "zstd 3" 
time bash ./timing2.bash 1 "$dataset" "zstd 4"
echo time bash ./timing2.bash 1 "$dataset" "zstd 4" 
time bash ./timing2.bash 1 "$dataset" "zstd 5"
echo time bash ./timing2.bash 1 "$dataset" "zstd 5" 
time bash ./timing2.bash 1 "$dataset" "zstd 6"
echo time bash ./timing2.bash 1 "$dataset" "zstd 6" 
time bash ./timing2.bash 1 "$dataset" "bszstd 2"
echo time bash ./timing2.bash 1 "$dataset" "bszstd 2" 
time bash ./timing2.bash 1 "$dataset" "bszstd 3"
echo time bash ./timing2.bash 1 "$dataset" "bszstd 3" 
time bash ./timing2.bash 1 "$dataset" "bszstd 4"
echo time bash ./timing2.bash 1 "$dataset" "bszstd 4" 
time bash ./timing2.bash 1 "$dataset" "bszstd 5"
echo time bash ./timing2.bash 1 "$dataset" "bszstd 5" 
time bash ./timing2.bash 1 "$dataset" "bszstd 6"
echo time bash ./timing2.bash 1 "$dataset" "bszstd 6" 
